### ISSUE TITLE
Questions about taxonomic binning challenge.

### ISSUE THREAD

**Issue by JaebeomKim0731** [CAMI-challenge/second_challenge_evaluation#14]
Hi, I'm Jaebeom Kim working on metagenomic classification.
I want to ask a question about reference databases used in the taxonomic binning challenge.

I can find three reference sequences on the CAMI2 web page: NCBI RefSeq, nt, and nr.
But as stated in [2nd CAMI Challenge Marine Dataset instruction](https://data.cami-challenge.org/participate), it seems like only nt and nr were provided as reference databases each for DNA-based tools and protein-based tools.
And RefSeq was not used as a reference database for the taxonomic binning challenge.

So, I want to check two things.
1) Is it right that only nt and nr were provided for taxonomic binning challenges using strain-madness and plant-associated datasets, too?
2) Then, when was the RefSeq used?

Thank you.

**Comment by fernandomeyer** [comment]
The CAMI 2 datasets were simulated from newly sequenced genomes and different sources, as described in the Methods section and supplement of the [CAMI 2 paper](https://doi.org/10.1038/s41592-022-01431-4). So the sequences in the datasets were not necessarily in RefSeq, nt, and nr at the time of the challenges, for any dataset.
RefSeq, nt, and nr, which are linked in the Databases tab at https://data.cami-challenge.org/participate, are just to be used as reference for any challenge for a fair benchmarking (see https://www.microbiome-cosi.org/cami/participate/cami-faq-frequently-asked-questions#compare-fairly).

**Comment by JaebeomKim0731** [comment]
Thank you for your reply!
Yes, I know that RefSeq, nt, and nr were not used to generate data for query.
They were provided to participants for database creation.
But in the "Marine Dataset" and "Strain Madness Dataset" instruction at https://data.cami-challenge.org/participate,
participants in taxonomic profiling and binning challenge were guided to use only nt or nr as their databases.
But the guidance is not written in the "Rhizosphere challenge" instruction.
So I want to check if the guidance is also applied  "Rhizosphere challenge".

If so, participants were allowed to use only nt or nr as databases in the taxonomic profiling and binning challenge. Right?
I just wanted to clarify this point because I'm testing different metagenomic classifiers using CAMI2 query data and databases.

Thank you again :)

**Comment by fernandomeyer** [comment]
The descriptions might be misleading, but the participants were allowed to use any database as reference. The descriptions don't ask to use _only_ those databases, but rather mean _If you use nt and nr as reference, then please use these ones_. We as challenge organizers wouldn't even have been able to validate a submission and check what reference the participants used.
Today, you can those databases as well if you want to. It's important that you don't use recent databases, released after the challenge, or purposely include sequences of the CAMI datasets like underlying genomes in your reference. Unfortunately, today it's easier to fine tune a method by doing that or by repeatedly validating it against the gold standards and targeting the results towards the number of taxa, which became public after the challenges. One should not use information that became public after the challenge for fair comparisons.
